version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'my-mongo-container'
    restart: never
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=fdrennan
      - MONGO_INITDB_ROOT_PASSWORD=thirdday1
    volumes:
      - ./init-mongo-js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - document-keeper:/data/db
    ports:
      - '27017:27017'
volumes:
  document-keeper: